### ISSUE TITLE
Document installation process on MacOS X

### ISSUE THREAD

**Issue by halfbro** [OpenRCT2/docs#7]
In order to complete the installation section, there should be a page of documentation detailing how to install OpenRCT2, similar to the one that already exists for Windows.

This page should cover common mistakes/issues (if any) when installing on MacOS.

In addition, maybe it would be useful to cover how to get the files from Steam, since it can't normally be downloaded for MacOS as far as I'm aware (you have to manually download the game files using a command line iirc).

**Comment by Gymnasiast** [comment]
I have now written this page. I have linked to the Wiki article about extracting from Steam/GOG/etc. I want to move that article to the docs at some point, but only when the docs cover most/all of the basic gameplay.
